version: '3'

services:
  engine:
      image: vuetify-docker:latest
      build: .
      container_name: vuetify-docker
      command: npm run dev
      volumes:
        - .:/vuetify-docker
      expose:
        - "4200"
      ports:
        - "4200:4200"
      environment:
        - IN_DOCKER=1
